prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/user_interfaces.sql
@@application/shared_components/navigation/lists/menu_di_navigazione.sql
@@application/shared_components/navigation/lists/barra_di_navigazione.sql
@@application/shared_components/navigation/lists/configurazione_applicazione.sql
@@application/shared_components/navigation/lists/interfaccia_utente.sql
@@application/shared_components/navigation/lists/report_attività.sql
@@application/shared_components/navigation/lists/controllo_dell_accesso.sql
@@application/shared_components/navigation/lists/feedback.sql
@@application/shared_components/navigation/lists/menu_home.sql
@@application/shared_components/navigation/lists/menu_anagrafiche.sql
@@application/shared_components/navigation/lists/menu_magazzino.sql
@@application/shared_components/navigation/lists/menu_anagrafiche_di_magazzino.sql
@@application/shared_components/navigation/lists/menu_produzione.sql
@@application/shared_components/navigation/lists/manu_anagrafiche_di_produzione.sql
@@application/shared_components/navigation/lists/creazione_contratto.sql
@@application/shared_components/files/icons_app_icon_32_png.sql
@@application/shared_components/files/icons_app_icon_192_png.sql
@@application/shared_components/files/icons_app_icon_512_png.sql
@@application/plugin_settings.sql
@@application/shared_components/security/authorizations/diritti_di_amministrazione.sql
@@application/shared_components/security/authorizations/diritti_lettore.sql
@@application/shared_components/security/authorizations/diritti_contributo.sql
@@application/shared_components/security/app_access_control/amministratore.sql
@@application/shared_components/security/app_access_control/collaboratore.sql
@@application/shared_components/security/app_access_control/processo_di_lettura.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/shared_components/user_interface/lovs/access_roles.sql
@@application/shared_components/user_interface/lovs/anag_fasi_prod_r_codfase_v_descr.sql
@@application/shared_components/user_interface/lovs/articoli.sql
@@application/shared_components/user_interface/lovs/articoli_codgm.sql
@@application/shared_components/user_interface/lovs/categorie_costo_distinta.sql
@@application/shared_components/user_interface/lovs/categorie_merceologiche.sql
@@application/shared_components/user_interface/lovs/clienti_fornitori_ragsoc.sql
@@application/shared_components/user_interface/lovs/codici_iva_descr.sql
@@application/shared_components/user_interface/lovs/conto_anag_descr.sql
@@application/shared_components/user_interface/lovs/costo_ass_perc_preventivo.sql
@@application/shared_components/user_interface/lovs/db_test_codart.sql
@@application/shared_components/user_interface/lovs/db_test_esp.sql
@@application/shared_components/user_interface/lovs/desktop_theme_styles.sql
@@application/shared_components/user_interface/lovs/email_username_format.sql
@@application/shared_components/user_interface/lovs/feedback_rating.sql
@@application/shared_components/user_interface/lovs/feedback_status.sql
@@application/shared_components/user_interface/lovs/gruppi_merceologici_stato.sql
@@application/shared_components/user_interface/lovs/gruppi_merc_codgm_descr.sql
@@application/shared_components/user_interface/lovs/gruppi_statistici_codgrst.sql
@@application/shared_components/user_interface/lovs/guide_testate_descr.sql
@@application/shared_components/user_interface/lovs/matricola_codmatricola.sql
@@application/shared_components/user_interface/lovs/p19_ricerca_codart.sql
@@application/shared_components/user_interface/lovs/p19_ricerca_codmat.sql
@@application/shared_components/user_interface/lovs/periodicità_contratti_statica.sql
@@application/shared_components/user_interface/lovs/si_no.sql
@@application/shared_components/user_interface/lovs/timeframe_4_weeks.sql
@@application/shared_components/user_interface/lovs/tipi_costo_preventivo.sql
@@application/shared_components/user_interface/lovs/tipi_ragg_iva_descr.sql
@@application/shared_components/user_interface/lovs/tipologie_descr.sql
@@application/shared_components/user_interface/lovs/unita_misura_um_descr.sql
@@application/shared_components/user_interface/lovs/un_prod_r_cod_v_descr.sql
@@application/shared_components/user_interface/lovs/user_theme_preference.sql
@@application/shared_components/user_interface/lovs/view_as_report_chart.sql
@@application/pages/page_groups.sql
@@application/comments.sql
@@application/shared_components/navigation/breadcrumbs/indicatore_di_percorso.sql
@@application/shared_components/navigation/breadcrumbentry.sql
@@application/shared_components/user_interface/templates/page/drawer.sql
@@application/shared_components/user_interface/templates/page/left_side_column.sql
@@application/shared_components/user_interface/templates/page/wizard_modal_dialog.sql
@@application/shared_components/user_interface/templates/page/left_and_right_side_columns.sql
@@application/shared_components/user_interface/templates/page/login.sql
@@application/shared_components/user_interface/templates/page/modal_dialog.sql
@@application/shared_components/user_interface/templates/page/master_detail.sql
@@application/shared_components/user_interface/templates/page/minimal_no_navigation.sql
@@application/shared_components/user_interface/templates/page/right_side_column.sql
@@application/shared_components/user_interface/templates/page/standard.sql
@@application/shared_components/user_interface/templates/button/icon.sql
@@application/shared_components/user_interface/templates/button/text.sql
@@application/shared_components/user_interface/templates/button/text_with_icon.sql
@@application/shared_components/user_interface/templates/region/alert.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes_no_grid.sql
@@application/shared_components/user_interface/templates/region/buttons_container.sql
@@application/shared_components/user_interface/templates/region/cards_container.sql
@@application/shared_components/user_interface/templates/region/carousel_container.sql
@@application/shared_components/user_interface/templates/region/collapsible.sql
@@application/shared_components/user_interface/templates/region/content_block.sql
@@application/shared_components/user_interface/templates/region/hero.sql
@@application/shared_components/user_interface/templates/region/image.sql
@@application/shared_components/user_interface/templates/region/inline_dialog.sql
@@application/shared_components/user_interface/templates/region/inline_drawer.sql
@@application/shared_components/user_interface/templates/region/interactive_report.sql
@@application/shared_components/user_interface/templates/region/item_container.sql
@@application/shared_components/user_interface/templates/region/login.sql
@@application/shared_components/user_interface/templates/region/search_results_container.sql
@@application/shared_components/user_interface/templates/region/standard.sql
@@application/shared_components/user_interface/templates/region/tabs_container.sql
@@application/shared_components/user_interface/templates/region/title_bar.sql
@@application/shared_components/user_interface/templates/region/wizard_container.sql
@@application/shared_components/user_interface/templates/region/inline_popup.sql
@@application/shared_components/user_interface/templates/list/badge_list.sql
@@application/shared_components/user_interface/templates/list/cards.sql
@@application/shared_components/user_interface/templates/list/media_list.sql
@@application/shared_components/user_interface/templates/list/menu_bar.sql
@@application/shared_components/user_interface/templates/list/navigation_bar.sql
@@application/shared_components/user_interface/templates/list/top_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/top_navigation_tabs.sql
@@application/shared_components/user_interface/templates/list/links_list.sql
@@application/shared_components/user_interface/templates/list/menu_popup.sql
@@application/shared_components/user_interface/templates/list/tabs.sql
@@application/shared_components/user_interface/templates/list/side_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/top_navigation_mega_menu.sql
@@application/shared_components/user_interface/templates/list/wizard_progress.sql
@@application/shared_components/user_interface/templates/report/alerts.sql
@@application/shared_components/user_interface/templates/report/badge_list.sql
@@application/shared_components/user_interface/templates/report/comments.sql
@@application/shared_components/user_interface/templates/report/contextual_info.sql
@@application/shared_components/user_interface/templates/report/media_list.sql
@@application/shared_components/user_interface/templates/report/standard.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_column.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_row.sql
@@application/shared_components/user_interface/templates/report/timeline.sql
@@application/shared_components/user_interface/templates/report/cards.sql
@@application/shared_components/user_interface/templates/report/search_results.sql
@@application/shared_components/user_interface/templates/report/content_row.sql
@@application/shared_components/user_interface/templates/label/hidden.sql
@@application/shared_components/user_interface/templates/label/optional.sql
@@application/shared_components/user_interface/templates/label/optional_above.sql
@@application/shared_components/user_interface/templates/label/optional_floating.sql
@@application/shared_components/user_interface/templates/label/required.sql
@@application/shared_components/user_interface/templates/label/required_above.sql
@@application/shared_components/user_interface/templates/label/required_floating.sql
@@application/shared_components/user_interface/templates/breadcrumb/breadcrumb.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/templates/calendar/calendar.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/globalization/translations.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/security/authentications/account_oracle_apex.sql
@@application/shared_components/navigation/search_config/prova.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00001.sql
@@application/pages/page_00002.sql
@@application/pages/page_00003.sql
@@application/pages/page_00004.sql
@@application/pages/page_00005.sql
@@application/pages/page_00006.sql
@@application/pages/page_00007.sql
@@application/pages/page_00008.sql
@@application/pages/page_00009.sql
@@application/pages/page_00010.sql
@@application/pages/page_00011.sql
@@application/pages/page_00012.sql
@@application/pages/page_00013.sql
@@application/pages/page_00014.sql
@@application/pages/page_00015.sql
@@application/pages/page_00016.sql
@@application/pages/page_00017.sql
@@application/pages/page_00018.sql
@@application/pages/page_00019.sql
@@application/pages/page_00020.sql
@@application/pages/page_00021.sql
@@application/pages/page_00022.sql
@@application/pages/page_00023.sql
@@application/pages/page_00024.sql
@@application/pages/page_00025.sql
@@application/pages/page_00026.sql
@@application/pages/page_00027.sql
@@application/pages/page_09999.sql
@@application/pages/page_10000.sql
@@application/pages/page_10010.sql
@@application/pages/page_10020.sql
@@application/pages/page_10030.sql
@@application/pages/page_10031.sql
@@application/pages/page_10032.sql
@@application/pages/page_10033.sql
@@application/pages/page_10034.sql
@@application/pages/page_10035.sql
@@application/pages/page_10036.sql
@@application/pages/page_10040.sql
@@application/pages/page_10041.sql
@@application/pages/page_10042.sql
@@application/pages/page_10043.sql
@@application/pages/page_10044.sql
@@application/pages/page_10050.sql
@@application/pages/page_10051.sql
@@application/pages/page_10053.sql
@@application/pages/page_10054.sql
@@application/pages/page_10060.sql
@@application/pages/page_10061.sql
@@application/deployment/definition.sql
@@application/deployment/checks.sql
@@application/deployment/buildoptions.sql
@@application/end_environment.sql
